name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Set up Docker
      run: |
        sudo chmod 666 /var/run/docker.sock
        sudo systemctl start docker

    - name: Build Docker image
      run: |
        docker build -t todo-app .

    - name: Deploy to EC2
      env:
        EC2_KEY: ${{ secrets.EC2_KEY_PAIR }}
      run: |
        echo "${EC2_KEY}" > ec2_key.pem
        chmod 400 ec2_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H 54.227.128.6 >> ~/.ssh/known_hosts
        scp -i ec2_key.pem app.py Dockerfile ubuntu@54.227.128.6:/home/ubuntu/ToDo_list/
        ssh -i ec2_key.pem ubuntu@54.227.128.6 "cd /home/ubuntu/ToDo_list/ && docker stop $(docker ps -q) || true && docker build -t todo-app . && docker run -d -p 80:5000 todo-app"
  
